[phases.setup]
nixPkgs = ['nodejs-18_x', 'npm']

[phases.install]
cmds = [
  'npm ci',
  'cd p2p-share && npm ci'
]

[phases.build]
cmds = [
  'cd p2p-share && npm run build'
]

[start]
cmd = 'node signaling-server/server.js'