services:
  - type: web
    name: p2p-signaling-server
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
    domains:
      - file-drop-backend.onrender.com