services:
  - type: web
    name: hikari-beam-frontend
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_SIGNALING_SERVER
        value: wss://hikari-beam-backend.onrender.com
