services:
  - type: web
    name: file-drop-frontend
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_SIGNALING_SERVER
        value: wss://file-drop-backend.onrender.com
