services:
  - type: web
    runtime: node
    plan: free
    rootDir: .
    buildCommand: npm ci && npm run build
    startCommand: npm start
    healthCheckPath: /
    dockerfilePath: ""
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_SIGNALING_SERVER
        value: wss://filedrop-backend.onrender.com
